import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, Mail, Menu, X } from 'lucide-react'
import { capabilities, experiences, technologies } from './data'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [active, setActive] = useState('top')
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-35% 0px -55% 0px' })
    document.querySelectorAll('section[id]').forEach((section) => observer.observe(section))
    return () => observer.disconnect()
  }, [])
  const jump = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <div className="site-shell">
    <header className="nav"><button className="brand" onClick={() => jump('top')}><span className="brand-mark">LJ</span><span>刘吉恒<span className="muted"> / SYSTEMS</span></span></button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{[['expertise','Expertise'],['experience','Experience'],['about','About']].map(([id,label]) => <button className={active === id ? 'nav-active' : ''} key={id} onClick={() => jump(id)}>{label}</button>)}<button className="nav-contact" onClick={() => jump('contact')}>Let’s talk <ArrowUpRight size={15}/></button></nav><button className="menu-btn" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></header>
    <main>
      <section className="hero section-pad" id="top"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> Available for new challenges <span className="slash">/</span> Beijing, CN</p><h1>Building<br/><em>systems</em><br/>that endure.</h1><p className="hero-lede">高级 Go 工程师，专注于高并发分布式系统、领域建模与复杂业务架构。让技术成为业务增长最可靠的底座。</p><div className="hero-actions"><button className="button-primary" onClick={() => jump('experience')}>View experience <ArrowDown size={17}/></button><button className="text-button" onClick={() => jump('contact')}>Get in touch <ArrowUpRight size={17}/></button></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core">GO<span>08</span></div><div className="node node-a">API<br/><small>99.99%</small></div><div className="node node-b">DOMAIN<br/><small>MODEL</small></div><div className="node node-c">DATA<br/><small>FLOW</small></div><div className="cross cross-a">+</div><div className="cross cross-b">+</div></div></div><div className="hero-footer"><span>Scroll to explore</span><span className="line"/><span>01 / 04</span></div></section>
      <section className="intro section-pad" id="expertise"><div className="section-kicker">01 — Expertise</div><div className="intro-content"><h2>把复杂，<br/><span>变成秩序。</span></h2><div><p className="big-copy">8 年 Go 实战经验，深耕高并发与分布式系统。擅长从 0 到 1 搭建高可用服务，也擅长在已有系统中找到下一步演进的路径。</p><p className="small-copy">我相信好的架构不只是技术的堆叠，而是清晰的边界、可验证的稳定性，以及对业务真正的理解。</p></div></div><div className="capability-grid">{capabilities.map((item) => <article className="capability" key={item.index}><span className="cap-index">{item.index}</span><h3>{item.title}</h3><p>{item.text}</p><ArrowUpRight className="cap-arrow" size={20}/></article>)}</div><div className="tech-row"><span className="tech-label">Toolbox</span><div className="tech-list">{technologies.map((tech) => <span key={tech}>{tech}</span>)}</div></div></section>
      <section className="experience section-pad" id="experience"><div className="section-kicker">02 — Experience</div><div className="experience-heading"><h2>轨迹，<br/><span>持续向深。</span></h2><p>从支付系统到共享出行营销平台，<br/>在不同规模的业务里解决同一个问题：<br/><strong>如何让系统值得信赖。</strong></p></div><div className="timeline">{experiences.map((item) => <article className="job" key={item.company}><div className="job-meta"><span>{item.label}</span><span>{item.period}</span></div><div className="job-main"><div><h3>{item.company}</h3><p className="role">{item.role} <span>/</span> {item.summary}</p></div><p className="job-detail">{item.detail}</p><div className="job-tags">{item.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="about section-pad" id="about"><div className="section-kicker">03 — About</div><div className="about-grid"><h2>技术之外，<br/><span>保持好奇。</span></h2><div className="about-text"><p>工程师的价值，不止是写出能运行的代码。更重要的是在不确定中建立确定性，在快速变化的需求里守住系统的长期健康。</p><div className="facts"><div><span>Education</span><strong>软件工程 · 本科</strong><small>西南民族大学 / 2011 — 2015</small></div><div><span>Certificate</span><strong>数据库系统工程师</strong><small>计算机技术与软件专业技术资格</small></div></div></div></div></section>
      <section className="contact section-pad" id="contact"><div className="contact-glow"/><div className="section-kicker">04 — Contact</div><div className="contact-content"><p className="eyebrow">Have a system to build?</p><h2>Let’s make<br/><em>it resilient.</em></h2><a className="contact-link" href="mailto:172881647@qq.com">172881647@qq.com <ArrowUpRight size={23}/></a><div className="socials"><a href="mailto:172881647@qq.com"><Mail size={17}/> Email</a><a href="https://github.com" target="_blank" rel="noreferrer">↗ Github</a><a href="https://linkedin.com" target="_blank" rel="noreferrer">↗ LinkedIn</a></div></div><footer><span>© 2026 Liu Jiheng</span><span>Designed & engineered with intention.</span></footer></section>
    </main>
  </div>
}
export default App
